/**
 * Frequently Asked Questions:
 * 
 * Q: Why does this file even exist?
 * 
 * A: __builtin_memcmp is currently broken on eBPF with LLVM 12 and this is the
 * only workaround I can come up with.
 * 
 */
if (name[0] == 's' && name[1] == 'n' && name[2] == 'a' && name[3] == 'p' && name[4] == 'd' && name[5] == '\0') block = true;
if (name[0] == 'b' && name[1] == 'r' && name[2] == 'a' && name[3] == 'v' && name[4] == 'e' && name[5] == '\0') cancel = true;
if (name[0] == 'b' && name[1] == 'r' && name[2] == 'a' && name[3] == 'v' && name[4] == 'e' && name[5] == '-' && name[6] == 'b' && name[7] == 'r' && name[8] == 'o' && name[9] == 'w' && name[10] == 's' && name[11] == 'e' && name[12] == 'r' && name[13] == '\0') cancel = true;
if (name[0] == 'b' && name[1] == 'r' && name[2] == 'a' && name[3] == 'v' && name[4] == 'e' && name[5] == '-' && name[6] == 'b' && name[7] == 'r' && name[8] == 'o' && name[9] == 'w' && name[10] == 's' && name[11] == 'e' && name[12] == 'r' && name[13] == '-' && name[14] == 's' && name[15] == 't' && name[16] == 'a' && name[17] == 'b' && name[18] == 'l' && name[19] == 'e' && name[20] == '\0') cancel = true;
if (name[0] == 'b' && name[1] == 'r' && name[2] == 'a' && name[3] == 'v' && name[4] == 'e' && name[5] == '-' && name[6] == 'b' && name[7] == 'r' && name[8] == 'o' && name[9] == 'w' && name[10] == 's' && name[11] == 'e' && name[12] == 'r' && name[13] == '-' && name[14] == 'b' && name[15] == 'e' && name[16] == 't' && name[17] == 'a' && name[18] == '\0') cancel = true;
if (name[0] == 'b' && name[1] == 'r' && name[2] == 'a' && name[3] == 'v' && name[4] == 'e' && name[5] == '-' && name[6] == 'b' && name[7] == 'r' && name[8] == 'o' && name[9] == 'w' && name[10] == 's' && name[11] == 'e' && name[12] == 'r' && name[13] == '-' && name[14] == 'n' && name[15] == 'i' && name[16] == 'g' && name[17] == 'h' && name[18] == 't' && name[19] == 'l' && name[20] == 'y' && name[21] == '\0') cancel = true;
